pyoso/__init__.py,sha256=rTEthT_bW2Uyj9gZ0E-ilhLtQH-PQdsWnpNPR1EZxzI,251
pyoso/client.py,sha256=OT_rCBZg74sMkCNc4h2FFnhIN4y7vEERRx8khthyHOo,2268
pyoso/exceptions.py,sha256=3S9gY6ndSmAENPPVYeY4tI6yyx91dngF0owZUykJUUM,278
pyoso-0.4.0.dist-info/METADATA,sha256=deYPgMoAXI_BZR0Souaf2HS4czbhlF6z7SgeoE6BSas,1159
pyoso-0.4.0.dist-info/WHEEL,sha256=qtCwoSJWgHk21S1Kb4ihdzI2rlJ1ZKaIurTj_ngOhyQ,87
pyoso-0.4.0.dist-info/RECORD,,
